### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by shashi278** [shashi278/TapTargetView#1]
#### TODO:
* [x] Track clicks inside `outer_circle`
* [x] Track clicks inside `target_circle` and remove the requirement of binding on widget's events
* [x] Add property to allow cancelling if clicked outside the `outer_circle`
* [x] Current implementation removes the elevation from the widget. Needs to be fixed.
* [ ] Add shadow property
* [ ] Better implementation of function to stop animation
* [ ] Improve ripple animation
